x-base-service: &base-service
  build:
    context: .
    dockerfile: containers/eqemu-server/Dockerfile
  environment: &base-environment
    DATABASE_USER: ${DATABASE_USER:-eq}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD:-eq}
    DATABASE_NAME: ${DATABASE_NAME:-eq}
    SERVER_ADDRESS: ${SERVER_ADDRESS}
    SERVER_SHORT_NAME: ${SERVER_SHORT_NAME:-EQMac Docker}
    SERVER_LONG_NAME: ${SERVER_LONG_NAME:-EQMac Docker}
    WAIT_HOSTS: db:3306

services:
  shared:
    <<: *base-service
    command: /app/shared_memory
    volumes:
      - shared:/app/shared
    depends_on:
      db:
        condition: service_started

  login:
    <<: *base-service
    command: /app/loginserver
    ports:
      - 6000:6000/tcp
      - 6000:6000/udp
    depends_on:
      db:
        condition: service_started
      shared:
        condition: service_completed_successfully

  world:
    <<: *base-service
    command: /app/world
    environment:
      <<: *base-environment
      WAIT_PATHS: /app/shared/spells
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
    volumes:
      - shared:/app/shared
    depends_on:
      db:
        condition: service_started
      login:
        condition: service_started
      shared:
        condition: service_completed_successfully

  zone:
    <<: *base-service
    command: ['/app/eqlaunch', 'dynzone1']
      #command: ['sleep', '50000']
    ports:
      - 7000-7374:7000-7374/tcp
      - 7000-7374:7000-7374/udp
    volumes:
      - shared:/app/shared
    depends_on:
      db:
        condition: service_started
      world:
        condition: service_started
      shared:
        condition: service_completed_successfully

  boats:
    <<: *base-service
    command: ['/app/eqlaunch', 'boats']
    ports:
      - 7375-7400:7375-7400/tcp
      - 7375-7400:7375-7400/udp
    volumes:
      - shared:/app/shared
    depends_on:
      db:
        condition: service_started
      world:
        condition: service_started
      shared:
        condition: service_completed_successfully

  queryserv:
    <<: *base-service
    command: /app/queryserv
    depends_on:
      db:
        condition: service_started
      world:
        condition: service_started
      shared:
        condition: service_completed_successfully

  ucs:
    <<: *base-service
    command: /app/ucs
    ports:
      - 7778:7778/tcp
      - 7778:7778/udp
    depends_on:
      db:
        condition: service_started
      world:
        condition: service_started
      shared:
        condition: service_completed_successfully

  db:
    build:
      context: .
      dockerfile: containers/database/Dockerfile
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: enabled
      MYSQL_USER: ${DATABASE_USER:-eq}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-eq}
      MYSQL_DATABASE: ${DATABASE_NAME:-eq}
    volumes:
      - database:/var/lib/mysql

volumes:
  shared:
  database:
